/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khan_captchareader_rarbgcaptcha_RarBGCaptchaReader */

#ifndef _Included_com_khan_captchareader_rarbgcaptcha_RarBGCaptchaReader
#define _Included_com_khan_captchareader_rarbgcaptcha_RarBGCaptchaReader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_khan_captchareader_rarbgcaptcha_RarBGCaptchaReader
 * Method:    readCaptha
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_khan_captchareader_rarbgcaptcha_RarBGCaptchaReader_readCaptha
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
